Bhvr approach client
AlexCampanozzi/HomoDeUS pull request #56
Opened 2021-11-24 21:02 UTC by AlexCampanozzi

2021-11-24 22:43 UTC, JMrobotUdes requested changes

2021-11-24 22:43 UTC, JMrobotUdes commented on homodeus_common/rosparams/homodeus_params.yaml
> +camera_mode: "robot"
yo on est en remote, je comprend pas

2021-11-24 22:43 UTC, JMrobotUdes commented on homodeus_external/base_navigation/scripts/navigator.py
> +
Tu peux te baser sur le get_state pour savoir si c'est fini ou pas

2021-11-24 22:43 UTC, JMrobotUdes commented on homodeus_hbba_cfg/hbba_cfg/bhvr_approach_client.yaml
> +        - cmd_vel
t'as vérifier que ca marchait?

2021-11-24 22:43 UTC, JMrobotUdes commented on homodeus_hbba_cfg/launch/all_simul.launch
> +  <param name="on_robot" type="bool" value="False" />
t'ajouteras ca à mon fichier dependencies.launch au lieu de polluer le all_simul.launch s'il-vous-plait

2021-11-24 22:43 UTC, JMrobotUdes commented on homodeus_common/landmarks.json
> +{"table1": [-1, -5.6, 0, 0, 0, -1.57],
Ça me dérange un peu d'avoir autant d'ajouts de goal pour un comportement

2021-11-25 01:34 UTC, AlexCampanozzi commented on homodeus_common/rosparams/homodeus_params.yaml
> +camera_mode: "robot"
remote ca prend la camera du laptop, alors que là je prenais la camera du robot dans la simul

2021-11-25 01:35 UTC, AlexCampanozzi commented on homodeus_hbba_cfg/hbba_cfg/bhvr_approach_client.yaml
> +        - cmd_vel
oui

2021-11-26 09:54 UTC, JMrobotUdes approved these changes

2021-11-26 09:54 UTC, merged